### ISSUE TITLE
Transparent text onto filled rect

### ISSUE THREAD

**Issue by nshzb** [bnielsen1965/oled-sh1106#1]
Hello,

I am using your library with pleasure, but i can't manage to get a transparent text (0 black pixel override) over a filledRect which is filled. 

Can you give me a working example ? I'm using the transparent flag on the font function but without success

Like in the following order

 ```
 display.drawFillRect(
                itemPosition.x,
                itemPosition.y,
                itemSize.width,
                itemSize.height,
                1
            );
        

        display.drawText(
            itemPosition.x,
            itemPosition.y,
            item.title,
            itemFont, >> this font = Display.fontToImageMap(require('my-font.js'), true)
            false
        );

```
Regards

**Comment by spljs** [comment]
I'm getting this 

![237012429_4565239956830782_8655077240014942763_n](https://user-images.githubusercontent.com/56301405/130369373-f3816779-68fb-4be6-863b-e8fb56e9947a.jpg)

**Comment by spljs** [comment]
I am using the following font

`
module.exports = {
    monospace: true,
    width: 5,
    height: 7,
    fontData: [
        0x00, 0x00, 0x00, 0x00, 0x00, // (space)
        0x00, 0x00, 0x5F, 0x00, 0x00, // !
        0x00, 0x07, 0x00, 0x07, 0x00, // "
        0x14, 0x7F, 0x14, 0x7F, 0x14, // #
        0x24, 0x2A, 0x7F, 0x2A, 0x12, // $
        0x23, 0x13, 0x08, 0x64, 0x62, // %
        0x36, 0x49, 0x55, 0x22, 0x50, // &
        0x00, 0x05, 0x03, 0x00, 0x00, // '
        0x00, 0x1C, 0x22, 0x41, 0x00, // (
        0x00, 0x41, 0x22, 0x1C, 0x00, // )
        0x08, 0x2A, 0x1C, 0x2A, 0x08, // *
        0x08, 0x08, 0x3E, 0x08, 0x08, // +
        0x00, 0x50, 0x30, 0x00, 0x00, // ,
        0x08, 0x08, 0x08, 0x08, 0x08, // -
        0x00, 0x60, 0x60, 0x00, 0x00, // .
        0x20, 0x10, 0x08, 0x04, 0x02, // /
        0x3E, 0x51, 0x49, 0x45, 0x3E, // 0
        0x00, 0x42, 0x7F, 0x40, 0x00, // 1
        0x42, 0x61, 0x51, 0x49, 0x46, // 2
        0x21, 0x41, 0x45, 0x4B, 0x31, // 3
        0x18, 0x14, 0x12, 0x7F, 0x10, // 4
        0x27, 0x45, 0x45, 0x45, 0x39, // 5
        0x3C, 0x4A, 0x49, 0x49, 0x30, // 6
        0x01, 0x71, 0x09, 0x05, 0x03, // 7
        0x36, 0x49, 0x49, 0x49, 0x36, // 8
        0x06, 0x49, 0x49, 0x29, 0x1E, // 9
        0x00, 0x36, 0x36, 0x00, 0x00, // :
        0x00, 0x56, 0x36, 0x00, 0x00, // ;
        0x00, 0x08, 0x14, 0x22, 0x41, // <
        0x14, 0x14, 0x14, 0x14, 0x14, // =
        0x41, 0x22, 0x14, 0x08, 0x00, // >
        0x02, 0x01, 0x51, 0x09, 0x06, // ?
        0x32, 0x49, 0x79, 0x41, 0x3E, // @
        0x7E, 0x11, 0x11, 0x11, 0x7E, // A
        0x7F, 0x49, 0x49, 0x49, 0x36, // B
        0x3E, 0x41, 0x41, 0x41, 0x22, // C
        0x7F, 0x41, 0x41, 0x22, 0x1C, // D
        0x7F, 0x49, 0x49, 0x49, 0x41, // E
        0x7F, 0x09, 0x09, 0x01, 0x01, // F
        0x3E, 0x41, 0x41, 0x51, 0x32, // G
        0x7F, 0x08, 0x08, 0x08, 0x7F, // H
        0x00, 0x41, 0x7F, 0x41, 0x00, // I
        0x20, 0x40, 0x41, 0x3F, 0x01, // J
        0x7F, 0x08, 0x14, 0x22, 0x41, // K
        0x7F, 0x40, 0x40, 0x40, 0x40, // L
        0x7F, 0x02, 0x04, 0x02, 0x7F, // M
        0x7F, 0x04, 0x08, 0x10, 0x7F, // N
        0x3E, 0x41, 0x41, 0x41, 0x3E, // O
        0x7F, 0x09, 0x09, 0x09, 0x06, // P
        0x3E, 0x41, 0x51, 0x21, 0x5E, // Q
        0x7F, 0x09, 0x19, 0x29, 0x46, // R
        0x46, 0x49, 0x49, 0x49, 0x31, // S
        0x01, 0x01, 0x7F, 0x01, 0x01, // T
        0x3F, 0x40, 0x40, 0x40, 0x3F, // U
        0x1F, 0x20, 0x40, 0x20, 0x1F, // V
        0x7F, 0x20, 0x18, 0x20, 0x7F, // W
        0x63, 0x14, 0x08, 0x14, 0x63, // X
        0x03, 0x04, 0x78, 0x04, 0x03, // Y
        0x61, 0x51, 0x49, 0x45, 0x43, // Z
        0x7D, 0x12, 0x12, 0x7D, 0x00, // Ä
        0x3D, 0x42, 0x42, 0x42, 0x3D, // Ö
        0x3D, 0x40, 0x40, 0x40, 0x3D, // Ü
        0x00, 0x00, 0x7F, 0x41, 0x41, // [
        0x02, 0x04, 0x08, 0x10, 0x20, // "\"
        0x41, 0x41, 0x7F, 0x00, 0x00, // ]
        0x04, 0x02, 0x01, 0x02, 0x04, // ^
        0x40, 0x40, 0x40, 0x40, 0x40, // _
        0x00, 0x01, 0x02, 0x04, 0x00, // `
        0x20, 0x54, 0x54, 0x54, 0x78, // a
        0x7F, 0x48, 0x44, 0x44, 0x38, // b
        0x38, 0x44, 0x44, 0x44, 0x20, // c
        0x38, 0x44, 0x44, 0x48, 0x7F, // d
        0x38, 0x54, 0x54, 0x54, 0x18, // e
        0x08, 0x7E, 0x09, 0x01, 0x02, // f
        0x08, 0x14, 0x54, 0x54, 0x3C, // g
        0x7F, 0x08, 0x04, 0x04, 0x78, // h
        0x00, 0x44, 0x7D, 0x40, 0x00, // i
        0x20, 0x40, 0x44, 0x3D, 0x00, // j
        0x00, 0x7F, 0x10, 0x28, 0x44, // k
        0x00, 0x41, 0x7F, 0x40, 0x00, // l
        0x7C, 0x04, 0x18, 0x04, 0x78, // m
        0x7C, 0x08, 0x04, 0x04, 0x78, // n
        0x38, 0x44, 0x44, 0x44, 0x38, // o
        0x7C, 0x14, 0x14, 0x14, 0x08, // p
        0x08, 0x14, 0x14, 0x18, 0x7C, // q
        0x7C, 0x08, 0x04, 0x04, 0x08, // r
        0x48, 0x54, 0x54, 0x54, 0x20, // s
        0x04, 0x3F, 0x44, 0x40, 0x20, // t
        0x3C, 0x40, 0x40, 0x20, 0x7C, // u
        0x1C, 0x20, 0x40, 0x20, 0x1C, // v
        0x3C, 0x40, 0x30, 0x40, 0x3C, // w
        0x44, 0x28, 0x10, 0x28, 0x44, // x
        0x0C, 0x50, 0x50, 0x50, 0x3C, // y
        0x44, 0x64, 0x54, 0x4C, 0x44, // z
        0x20, 0x55, 0x54, 0x55, 0x78, // ä
        0x3A, 0x44, 0x44, 0x3A, 0x00, // ö
        0x3A, 0x40, 0x40, 0x3A, 0x00, // ü
        0x00, 0x08, 0x36, 0x41, 0x00, // {
        0x00, 0x00, 0x7F, 0x00, 0x00, // |
        0x00, 0x41, 0x36, 0x08, 0x00, // }
        0x14, 0x3E, 0x55, 0x41, 0x22, // €
        0x08, 0x08, 0x2A, 0x1C, 0x08, // -> (ALT + 0134) †
        0x08, 0x1C, 0x2A, 0x08, 0x08, // <- (ALT + 0135) ‡
        0x00, 0x00, 0x07, 0x05, 0x07  // °
    ],
    lookup: [' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/',
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@',
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q',
        'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Ä', 'Ö', 'Ü', '[', '\\', ']', '^', '_', '`',
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q',
        'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ä', 'ö', 'ü', '{', '|', '}', '€', '†', '‡', '°'
    ]
};

`

**Comment by bnielsen1965** [comment]
This is from the example folder in the project, I downloaded your font and put it in myfont.js then changed to test code to draw a filled rectangle and then draw a string with a regular font and then a transparent font.

Seemed to work ok, the first line with the non-transparent is visible on the filled rectangle, while the second line with the transparent font cannot be seen due to the filled rectangle.

I assume the drawText() method is something you added to the library, is it possible that it is not using the transparent font image map you created and instead is maybe using some other global map or something you left behind from testing or development?

![oled-ssh1106](https://user-images.githubusercontent.com/486139/130378960-939d9c8f-abb4-4ab2-bb6d-7ddbb82c0368.png)

```javascript
// using the rpio module for GPIO and SPI interface
const RPIO = require('rpio');

// GPIO numbers for ssh1106 functions
const PIN_RESET = 25;
const PIN_DATA_COMMAND = 24;

// use GPIOxx numbering and /dev/mem for i2c/PWM/SPI (requires running with sudo, i.e. sudo node index.js)
RPIO.init({ mapping: 'gpio' });
RPIO.init({ gpiomem: false });

// initialize SPI interface
RPIO.spiBegin();
RPIO.spiChipSelect(0);
RPIO.spiSetClockDivider(256);
RPIO.spiSetDataMode(0);

// configure function pins
RPIO.open(PIN_RESET, RPIO.OUTPUT, RPIO.HIGH);
RPIO.open(PIN_DATA_COMMAND, RPIO.OUTPUT, RPIO.LOW);

// create and configure sh1106 display driver
const SH1106 = require('../lib/index.js'); // example uses relative path for ssh1106 module
const Display = SH1106({
  sendCommand: transferArray,  // must provide a method to transfer byte array in command mode
  sendData: transferDataArray, // must provide a method to transfer byte array in data mode
  hardwareReset: resetDevice,  // must provide a method to reset the hardware
  displayColumns: 128,
  displayRows: 64,
  columnOffset: 2,
  multiplexRatio: 0x3F,
  commonPadConfig: 0x12
});

// load test fonts and convert to image map
const MyFont = require('./myfont');
const MyFontIMTransparent = Display.fontToImageMap(MyFont, true);
const MyFontIM = Display.fontToImageMap(MyFont);

// initialize the display
Display.init()
.then(() => {
  // start in upper left corner
  Display.setCursor(0, 0);
  Display.drawFillRect(0, 0, 128, 64, 1);

  // use my font to draw string
  Display.drawString('Hello world!\n', MyFontIM);
  // draw another string with transparent font, should not show due to filled rect
  Display.drawString('Second Line\n', MyFontIMTransparent);
  return Display.updateDisplay();
})
.then(() => {
  console.log('Complete');
  process.exit(0);
})
.catch(err => {
  console.log('ERR', err.message, err.stack);
  process.exit(1);
});


// switch to data command mode then transfer data over SPI
async function transferDataArray(data) {
  RPIO.write(PIN_DATA_COMMAND, 1);
  await transferArray(data);
  RPIO.write(PIN_DATA_COMMAND, 0);
}

// transfer data over SPI
async function transferArray(data) {
  let rxBuff = new Buffer(data.length);
  RPIO.spiTransfer(Buffer.from(data), rxBuff, data.length);
  return rxBuff;
}

// toggle reset pin on the SH1106 device
async function resetDevice() {
  await setReset(RPIO.HIGH, 500)
  await setReset(RPIO.LOW, 500);
  await setReset(RPIO.HIGH, 3000);
}

// set reset pin value with optional delay
function setReset(v, d) {
	return new Promise((resolve, reject) => {
		RPIO.write(PIN_RESET, v);
		setTimeout(() => { resolve(); }, d);
	});
}
```

**Comment by spljs** [comment]
Thanks for the reply ! I have rewritten the fontToImageMap() function in order to get a better result. If you wanna check it out 

```
fontToImageMap(font, transparent) {
        let fontIM = {width: font.width, height: font.height};
        let colPages = Math.ceil(font.height / 8); // number of byte pages to represent column
        let charBytes = colPages * font.width; // bytes per character
        let padBits = (colPages * 8) % font.height; // height may be less total bit height
        for (let li = 0; li < font.lookup.length; li++) {
            let idata = [];
            let cdata = font.fontData.slice(li * charBytes, (li + 1) * charBytes);
            for (let p = 0; p < colPages; p++) {
                for (let b = 0; b < 8; b++) {
                    if (!p && b >= 8 - padBits) {
                        continue;
                    } // first page may have padding bits
                    let bitMask = 0x01 << b; // create mask for this bit position in char byte
                    for (let c = 0; c < font.width; c++) {
                        if (transparent) {
                            let pixelState = cdata[c + p * font.width] & bitMask ? 0 : 1;
                            idata.push(pixelState);
                            idata.push(0xff);
                        } else {
                            let pixelState = cdata[c + p * font.width] & bitMask ? 1 : 0;
                            idata.push(pixelState);
                        }

                    }
                }
            }
            fontIM[font.lookup[li]] = {
                width: font.width,
                height: font.height,
                channels: (transparent ? 2 : 1),
                data: Buffer.from(idata)
            };
        }
        return fontIM;
    }
```

Thanks again for the library you saved me a plenty of time !

![237498420_523417132070344_3519096134785329113_n](https://user-images.githubusercontent.com/56301405/130437261-d310c578-c6d0-46c6-8961-1ab19184ef32.jpg)

**Comment by bnielsen1965** [comment]
I think this change to the image map will create an inverted transparent image...

```javascript
if (transparent) {
                            let pixelState = cdata[c + p * font.width] & bitMask ? 0 : 1;
                            idata.push(pixelState);
                            idata.push(0xff);
                        } else {
                            let pixelState = cdata[c + p * font.width] & bitMask ? 1 : 0;
                            idata.push(pixelState);
                        }
```

Were you trying to create an inverted font to use on a "white" background?

I hadn't thought about inverted fonts, I like the idea but it would need to be implemented as a separate feature from the transparency.

On a side note, several months back I started a new project where I was implementing OLED drivers...
[oily-wm](https://github.com/bnielsen1965/oily-wm)
The objective was to create a small window manager that would allow you to have multiple managed windows. Part of that includes a new driver for the sh1106 OLED...
[oily-driver-sh1106](https://github.com/bnielsen1965/oily-wm/tree/main/packages/oily-driver-sh1106)

If we make changes to oled-sh1106 then I'll propogate them to the oily-wm, or if you would like to use the oily-driver-sh1106 we can make improvements there.

**Comment by spljs** [comment]
Yeah i though you meant that by transparency. If i have time I can implement it in a cleaner version of the code i gave you, it might be useful
